# -*- coding: utf-8 -*-
"""matplotlibipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-bf_HVVD6OblG6DKETQ5xd113L7N8_k
"""

import matplotlib.pyplot as plt

import pandas as pd
df = pd.read_excel('/content/Excel Food Delivery Project.xlsx')

df

df.head()

import matplotlib
print(matplotlib.__version__)

plt.plot([1, 2, 3], [4, 5, 6])
plt.title("Test Plot")
plt.show()

df['City'].value_counts().plot(kind='bar')
plt.title("Orders per City")
plt.show()

df['Delivery_status'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Order Status")
plt.show()

plt.hist(df['Rating'])
plt.title("Customer Ratings")
plt.show()

plt.hist(df['Price'])
plt.title("Order Price Distribution")
plt.show()

plt.hist(df['Quantity'])
plt.title("Quantity Ordered")
plt.show()

plt.scatter(df['Price'], df['Rating'])
plt.xlabel("Price")
plt.ylabel("Rating")
plt.show()

plt.scatter(df['Quantity'], df['Price'])
plt.show()

df['Order_date'] = pd.to_datetime(df['Order_date'])
df.groupby(df['Order_date'].dt.day).size().plot()
plt.title("Orders per Day")
plt.show()

df.groupby(df['Order_date'].dt.month).size().plot()
plt.title("Orders per Month")
plt.show()

df['weekday'] = df['Order_date'].dt.day_name()
df['weekday'].value_counts().plot(kind='bar')
plt.show()

df.groupby('City')['Price'].mean().plot(kind='bar')
plt.title("Avg Price per City")
plt.show()

df.groupby('City')['Rating'].mean().plot(kind='bar')
plt.show()

df['City'].value_counts().head(10).plot(kind='bar')
plt.show()

plt.boxplot(df['Price'])
plt.title("Price Outliers")
plt.show()

plt.boxplot(df['Rating'])
plt.show()

plt.boxplot(df['Quantity'])
plt.show()

df['Orders'] = 1
df['Orders'].cumsum().plot()
plt.title("Cumulative Orders")
plt.show()

df_sorted = df.sort_values('Price')
plt.plot(df_sorted['Price'])
plt.show()

plt.plot(df['Rating'])
plt.show()

df.groupby('Order_date').size().plot()
plt.show()

plt.plot(df['Price'], df['Quantity'])
plt.show()

plt.scatter(df['Delivery_status'], df['Price'])
plt.show()

plt.bar(df['City'], df['Quantity'])
plt.xticks(rotation=90)
plt.show()

plt.scatter(df['Rating'], df['Quantity'])
plt.show()