# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_SzLjyXJ41GhMagwSSVJOLBlM7v7lmH
"""

import numpy as np

np.__version__

import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_excel('Excel Food Delivery Project.xlsx')
df

data = df.values
data

arr = np.array(data)
arr

arr.shape

arr.ndim

arr[0]

pd.isna(arr).sum().sum()

arr = np.nan_to_num(arr)
arr

np.mean(arr[:, 10])

np.median(arr[:, 10])

np.std(arr[:, 10])

np.min(arr[:, 10])

np.max(arr[:, 10])

arr_price_column = arr[:, 10].astype(float)
arr_price_column

(
(arr_price_column - np.min(arr_price_column)) /
(np.max(arr_price_column) - np.min(arr_price_column))
)

arr.reshape(-1, 1)

arr.flatten()

arr_price_column[arr_price_column > 0]

np.random.choice(arr.flatten(), size=5)

np.split(arr, 2)

df_new = pd.DataFrame(arr)

df_new

arr[:, 5] = pd.to_datetime(arr[:, 5], errors='coerce').normalize().values

print(arr)