# -*- coding: utf-8 -*-
"""Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AneiVSUgunAfAGElBeL4BLq5uNQm4v5w
"""

import pandas as pd

df = pd.read_excel('/content/Excel Food Delivery Project.xlsx')

df

df.head()

df.tail()

df.head(3)

df.tail(3)

df.shape

df.columns

df.dtypes

df.info()

df.describe()

df.isnull().sum()

df.fillna(method='ffill', inplace=True)

df.dropna(inplace=True)
df

df.drop_duplicates(inplace=True)
df

df.columns = df.columns.str.lower().str.replace(" ", "_")
df

df['order_date'] = pd.to_datetime(df['order_date'])
df

df = df[df['rating'] > 3]
df

df.sort_values(by='delivery_status', inplace=True)
df

df.groupby('city')['delivery_status'].value_counts()
df

df['month'] = df['order_date'].dt.month
df

df = pd.get_dummies(df, columns=['city'])
df

df.drop(['order_id'], axis=0, inplace=True, errors='ignore')
df

df.to_csv('/content/cleaned_data.csv', index=False)
df

